package com.jfinal.qyweixin.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setAgentId(java.lang.String agentId) {
		set("agent_id", agentId);
	}

	public java.lang.String getAgentId() {
		return get("agent_id");
	}

	public void setCorpId(java.lang.String corpId) {
		set("corp_id", corpId);
	}

	public java.lang.String getCorpId() {
		return get("corp_id");
	}

	public void setSecret(java.lang.String secret) {
		set("secret", secret);
	}

	public java.lang.String getSecret() {
		return get("secret");
	}

	public void setEncodingaeskey(java.lang.String encodingaeskey) {
		set("encodingaeskey", encodingaeskey);
	}

	public java.lang.String getEncodingaeskey() {
		return get("encodingaeskey");
	}

	public void setRmid(java.lang.String rmid) {
		set("rmid", rmid);
	}

	public java.lang.String getRmid() {
		return get("rmid");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
