package com.jfinal.qyweixin.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRight<M extends BaseUserRight<M>> extends Model<M> implements IBean {

	public void setIdInTable(java.lang.Integer idInTable) {
		set("id_in_table", idInTable);
	}

	public java.lang.Integer getIdInTable() {
		return get("id_in_table");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setLineId(java.lang.String lineId) {
		set("line_id", lineId);
	}

	public java.lang.String getLineId() {
		return get("line_id");
	}

	public void setRodId(java.lang.String rodId) {
		set("rod_id", rodId);
	}

	public java.lang.String getRodId() {
		return get("rod_id");
	}

	public void setCrowEstRoughLen(java.lang.String crowEstRoughLen) {
		set("crow_est_rough_len", crowEstRoughLen);
	}

	public java.lang.String getCrowEstRoughLen() {
		return get("crow_est_rough_len");
	}

	public void setCrowDate(java.lang.String crowDate) {
		set("crow_date", crowDate);
	}

	public java.lang.String getCrowDate() {
		return get("crow_date");
	}

	public void setCrowEstExactLen(java.lang.String crowEstExactLen) {
		set("crow_est_exact_len", crowEstExactLen);
	}

	public java.lang.String getCrowEstExactLen() {
		return get("crow_est_exact_len");
	}

	public void setCrowTotalLen(java.lang.String crowTotalLen) {
		set("crow_total_len", crowTotalLen);
	}

	public java.lang.String getCrowTotalLen() {
		return get("crow_total_len");
	}

	public void setCrowStickLen(java.lang.String crowStickLen) {
		set("crow_stick_len", crowStickLen);
	}

	public java.lang.String getCrowStickLen() {
		return get("crow_stick_len");
	}

	public void setCrowMacId(java.lang.String crowMacId) {
		set("crow_mac_id", crowMacId);
	}

	public java.lang.String getCrowMacId() {
		return get("crow_mac_id");
	}

	public void setCutDate(java.lang.String cutDate) {
		set("cut_date", cutDate);
	}

	public java.lang.String getCutDate() {
		return get("cut_date");
	}

	public void setCrowOperator(java.lang.String crowOperator) {
		set("crow_operator", crowOperator);
	}

	public java.lang.String getCrowOperator() {
		return get("crow_operator");
	}

	public void setCutLen(java.lang.String cutLen) {
		set("cut_len", cutLen);
	}

	public java.lang.String getCutLen() {
		return get("cut_len");
	}

	public void setCutPreLen(java.lang.String cutPreLen) {
		set("cut_pre_len", cutPreLen);
	}

	public java.lang.String getCutPreLen() {
		return get("cut_pre_len");
	}

	public void setCutBubLen(java.lang.String cutBubLen) {
		set("cut_bub_len", cutBubLen);
	}

	public java.lang.String getCutBubLen() {
		return get("cut_bub_len");
	}

	public void setCutCryLen(java.lang.String cutCryLen) {
		set("cut_cry_len", cutCryLen);
	}

	public java.lang.String getCutCryLen() {
		return get("cut_cry_len");
	}

	public void setCutCrack(java.lang.String cutCrack) {
		set("cut_crack", cutCrack);
	}

	public java.lang.String getCutCrack() {
		return get("cut_crack");
	}

	public void setCutCrackLen(java.lang.String cutCrackLen) {
		set("cut_crack_len", cutCrackLen);
	}

	public java.lang.String getCutCrackLen() {
		return get("cut_crack_len");
	}

	public void setCutOperator(java.lang.String cutOperator) {
		set("cut_operator", cutOperator);
	}

	public java.lang.String getCutOperator() {
		return get("cut_operator");
	}

	public void setRubDate(java.lang.String rubDate) {
		set("rub_date", rubDate);
	}

	public java.lang.String getRubDate() {
		return get("rub_date");
	}

	public void setRubOperator(java.lang.String rubOperator) {
		set("rub_operator", rubOperator);
	}

	public java.lang.String getRubOperator() {
		return get("rub_operator");
	}

	public void setRubLen(java.lang.String rubLen) {
		set("rub_len", rubLen);
	}

	public java.lang.String getRubLen() {
		return get("rub_len");
	}

	public void setRollDate(java.lang.String rollDate) {
		set("roll_date", rollDate);
	}

	public java.lang.String getRollDate() {
		return get("roll_date");
	}

	public void setRollOperator(java.lang.String rollOperator) {
		set("roll_operator", rollOperator);
	}

	public java.lang.String getRollOperator() {
		return get("roll_operator");
	}

	public void setRollLen(java.lang.String rollLen) {
		set("roll_len", rollLen);
	}

	public java.lang.String getRollLen() {
		return get("roll_len");
	}

	public void setOfDate(java.lang.String ofDate) {
		set("of_date", ofDate);
	}

	public java.lang.String getOfDate() {
		return get("of_date");
	}

	public void setOfOperator(java.lang.String ofOperator) {
		set("of_operator", ofOperator);
	}

	public java.lang.String getOfOperator() {
		return get("of_operator");
	}

	public void setOfLen(java.lang.String ofLen) {
		set("of_len", ofLen);
	}

	public java.lang.String getOfLen() {
		return get("of_len");
	}

	public void setOfFormat(java.lang.String ofFormat) {
		set("of_format", ofFormat);
	}

	public java.lang.String getOfFormat() {
		return get("of_format");
	}

	public void setOfCollap(java.lang.String ofCollap) {
		set("of_collap", ofCollap);
	}

	public java.lang.String getOfCollap() {
		return get("of_collap");
	}

	public void setFinalBub(java.lang.String finalBub) {
		set("final_bub", finalBub);
	}

	public java.lang.String getFinalBub() {
		return get("final_bub");
	}

	public void setFinalCrack(java.lang.String finalCrack) {
		set("final_crack", finalCrack);
	}

	public java.lang.String getFinalCrack() {
		return get("final_crack");
	}

	public void setFinalDate(java.lang.String finalDate) {
		set("final_date", finalDate);
	}

	public java.lang.String getFinalDate() {
		return get("final_date");
	}

	public void setFinalTotalLen(java.lang.String finalTotalLen) {
		set("final_total_len", finalTotalLen);
	}

	public java.lang.String getFinalTotalLen() {
		return get("final_total_len");
	}

	public void setFinalExactLen(java.lang.String finalExactLen) {
		set("final_exact_len", finalExactLen);
	}

	public java.lang.String getFinalExactLen() {
		return get("final_exact_len");
	}

	public void setAddInfo(java.lang.String addInfo) {
		set("add_info", addInfo);
	}

	public java.lang.String getAddInfo() {
		return get("add_info");
	}

}
