package com.jfinal.qyweixin.demo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("qywx_authorize", "id", Authorize.class);
		arp.addMapping("qywx_config", "id", Config.class);
		arp.addMapping("qywx_crystal_stick_statistics", "id", CrystalStickStatistics.class);
		arp.addMapping("qywx_user_right", "id_in_table", UserRight.class);
	}
}

