package com.jfinal.qyweixin.demo.model;

import com.jfinal.qyweixin.demo.model.base.BaseAuthorize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authorize extends BaseAuthorize<Authorize> {
	
}
