package com.jfinal.qyweixin.demo.model;

import com.jfinal.qyweixin.demo.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	
}
