package com.jfinal.qyweixin.demo.model;

import com.jfinal.qyweixin.demo.model.base.BaseCrystalStickStatistics;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrystalStickStatistics extends BaseCrystalStickStatistics<CrystalStickStatistics> {

    public static final CrystalStickStatistics dao = new CrystalStickStatistics().dao();

}
