package com.jfinal.qyweixin.demo.model;

import com.jfinal.qyweixin.demo.model.base.BaseUserRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRight extends BaseUserRight<UserRight> {
    public static final UserRight dao = new UserRight().dao();
}
