package com.jfinal.qyweixin.demo.model;

import com.jfinal.qyweixin.demo.model.base.BaseWxAuthorize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxAuthorize extends BaseWxAuthorize<WxAuthorize> {
	
}
